# Generated by Django 3.2.5 on 2021-07-19 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apparel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('website', models.CharField(max_length=255)),
                ('apparels', models.ManyToManyField(related_name='brands', to='shop_project.Apparel')),
            ],
        ),
        migrations.CreateModel(
            name='PriceRange',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('google_link', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('brands', models.ManyToManyField(related_name='shops', to='shop_project.Brand')),
            ],
        ),
        migrations.AddField(
            model_name='brand',
            name='price_range',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_project.pricerange'),
        ),
    ]
