# Generated by Django 3.2.5 on 2021-07-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='apparels',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='brands',
        ),
        migrations.AddField(
            model_name='apparel',
            name='brands',
            field=models.ManyToManyField(related_name='apparels', to='shop_project.Brand'),
        ),
        migrations.AddField(
            model_name='brand',
            name='shops',
            field=models.ManyToManyField(related_name='brands', to='shop_project.Shop'),
        ),
    ]
